server:
  port: 30004
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://192.168.1.108:3306/leyou?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  redis:
    host: 192.168.1.100
  rabbitmq:
    host: 192.168.1.100
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      retry:
        enabled: true
        multiplier: 2
        initial-interval: 10000ms
        max-interval: 210000ms
      exchange: leyou.item.exchange
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.102:30002/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 192.168.1.102
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

ribbon:
  ConnectTimeout: 4000 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms